/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ameri.swing;

import com.ameri.backend.Verificacion;
import com.ameri.enums.Orden;
import com.ameri.modelos.Resultado;

import javax.swing.*;

/**
 *
 * @author ameri
 */
public class FrameResultados extends javax.swing.JDialog {

    /**
     * Creates new form FrameResultados
     */
    private FramePrincipal principal;

    public FrameResultados(FramePrincipal principal, boolean modal) {
        super(principal, modal);
        initComponents();
        this.setLocationRelativeTo(principal);
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPosicionSeis = new javax.swing.JTextField();
        textoPosicionCinco = new javax.swing.JTextField();
        textoPosicionSiete = new javax.swing.JTextField();
        textoPosicionOcho = new javax.swing.JTextField();
        textoPosicionNueve = new javax.swing.JTextField();
        textoPosicionDiez = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoGanador = new javax.swing.JTextField();
        textoPosicionDos = new javax.swing.JTextField();
        textoPosicionTres = new javax.swing.JTextField();
        textoPosicionCuatro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonGuardarRes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel5.setText("Número del caballo de la 2da posición:");

        jLabel6.setText("Número del caballo de la 4ta posición:");

        jLabel7.setText("Número del caballo de la 5ta posición:");

        jLabel8.setText("Número del caballo de la 7ma posición:");

        jLabel9.setText("Número del caballo de la 6ta posición:");

        jLabel10.setText("Número del caballo en la 8va posición:");

        jLabel11.setText("Número del caballo en la 9na posición:");

        jLabel12.setText("Número del caballo de la 10ma posición:");

        jLabel13.setText("Número del caballo de la 3ra posición:");

        jLabel4.setText("Número del caballo ganador:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESO DE RESULTADOS");

        botonGuardarRes.setText("Registrar Resultados");
        botonGuardarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarResActionPerformed(evt);
            }
        });

        jLabel2.setText("Orden de los resultados:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alfabético", "Numérico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(botonGuardarRes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoPosicionDos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoGanador, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionDiez, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionNueve, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionOcho, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionSiete, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionSeis, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionCinco, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionTres, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(textoPosicionCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPosicionDiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonGuardarRes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarResActionPerformed
        // TODO add your handling code here:
        this.principal.setResultado(null);
        try{

            int primerPos = Integer.parseInt(textoGanador.getText());
            int segundaPos = Integer.parseInt(textoPosicionDos.getText());
            int terceraPos = Integer.parseInt(textoPosicionTres.getText());
            int cuartaPos = Integer.parseInt(textoPosicionCuatro.getText());
            int quintaPos = Integer.parseInt(textoPosicionCinco.getText());
            int sextaPos = Integer.parseInt(textoPosicionSeis.getText());
            int septimaPos = Integer.parseInt(textoPosicionSiete.getText());
            int octavaPos = Integer.parseInt(textoPosicionOcho.getText());
            int novenaPos = Integer.parseInt(textoPosicionNueve.getText());
            int decimaPos = Integer.parseInt(textoPosicionDiez.getText());
            String ordenamiento = (String)jComboBox1.getSelectedItem();

            System.out.println("ordenamiento = " + ordenamiento);
            int[] resultados = {primerPos,segundaPos,terceraPos,cuartaPos,quintaPos,sextaPos,septimaPos,octavaPos,novenaPos,decimaPos};
            if(!new Verificacion().verificarResultadosRepetidos(resultados) && ordenamiento != null){
                this.principal.setResultado(new Resultado(resultados));
                this.principal.setOrden(Orden.obtenerOrden(ordenamiento));

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar los resultados por valores inválidos o repetidos.", "Información", JOptionPane.ERROR_MESSAGE);
            }


        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error al registrar los resultados por valores inválidos.", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarResActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarRes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textoGanador;
    private javax.swing.JTextField textoPosicionCinco;
    private javax.swing.JTextField textoPosicionCuatro;
    private javax.swing.JTextField textoPosicionDiez;
    private javax.swing.JTextField textoPosicionDos;
    private javax.swing.JTextField textoPosicionNueve;
    private javax.swing.JTextField textoPosicionOcho;
    private javax.swing.JTextField textoPosicionSeis;
    private javax.swing.JTextField textoPosicionSiete;
    private javax.swing.JTextField textoPosicionTres;
    // End of variables declaration//GEN-END:variables
}
